NLP visualization
Alvearie/patient-browser pull request #4
Opened 2021-07-28 17:09 UTC by KathrynElrod

2021-07-29 20:29 UTC, cragun47 requested changes
Remove confidential content; move inline styles to classes; reduce complex logic blocks.   See comments.

Good work!

2021-07-29 20:29 UTC, cragun47 commented on src/components/Fhir/InsightsDetailButton.js
> +                    <div style={{boxShadow: "0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)"}} className="panel panel-default">
Inline style.

2021-07-29 20:29 UTC, cragun47 commented on src/components/Fhir/InsightsDetailButton.js
> +                            <table className="table table-condensed table-hover table-striped table-bordered">
You probably don't have accessibility as a requirement, but an easy add is If the table is being used for layout only, add  role="presentation".  (https://fae.disability.illinois.edu/rulesets/TABLE_5/)

2021-07-29 20:29 UTC, cragun47 commented on src/components/Fhir/ResourceList.js
> +                            <tr key={i} className={o.isNLP ? "mark" : ""}>
Better style changing using ternary then adding / removing a class.   Good job.

2021-07-29 20:29 UTC, cragun47 commented on src/components/Fhir/ResourceList.js
> +                    style={{
Change inline styles to .css classes.

2021-07-29 20:29 UTC, cragun47 commented on src/lib/index.js
> +                if (getPath(ext_outer[item_outer], "url") == "http://ibm.com/fhir/cdm/insight/result") {
Very deep conditional and looping logic.  Should refactor to digestible subroutines.  Use the subroutine names to document what is going on.  Example:

```javascript
 for (let item_inner in ext_inner) {
                             let url = getPath(ext_inner[item_inner], "url")
                             // now that we've got the url, find all the different bits
                             result = gatherInsightsForInnerItem(result, url)
                             }
```

2021-07-30 14:12 UTC, KathrynElrod commented on src/components/Fhir/InsightsDetailButton.js
> +        let deets = getInsightDetails(rec)
Renamed to `details`.

2021-07-30 14:13 UTC, KathrynElrod commented on src/components/Fhir/InsightsDetailButton.js
> +                            <table className="table table-condensed table-hover table-striped table-bordered">
accessibility should always be a requirement -- thanks for the tip!

2021-07-30 17:41 UTC, KathrynElrod commented on build/js/report.html
> + */
I believe this is a report file generated for the developer, and is not included in the built application. 
![image](https://user-images.githubusercontent.com/47434066/127691469-ab47ac4f-4e7e-4587-8379-9c1b8d244c0d.png)

2021-07-30 17:44 UTC, KathrynElrod commented on src/components/Fhir/Grid/index.js
> +            <tr key={i}>
This is not code added by me -- rather, I removed the `onClick` and `style` parameters and condensed the block into a single line.

2021-08-02 14:24 UTC, cragun47 commented on build/js/report.html
> + */
Why is it in the HTML?   IMO, if we are going to keep it, it is something that I think Eric should be made aware of and approve.

2021-08-02 14:26 UTC, cragun47 commented on src/components/Fhir/Grid/index.js
> +            <tr key={i}>
Good solution!

2021-08-02 14:30 UTC, cragun47 approved these changes
Approved.  Minor recommendations.

2021-08-02 14:30 UTC, cragun47 commented on src/components/Fhir/InsightsDetailButton.js
> +                                <i className="fa fa-lightbulb-o fas fa-bold" style={{paddingRight: 10}}/>Insights for {rec.resourceType} {rec.id}
Move inline styles to class.

2021-08-02 14:30 UTC, cragun47 commented on src/components/Fhir/ResourceList.js
> +                                <td className="label-cell" style={o.isHighlight ? {color: "white"} : null}>{ o.label }</td>
Recommend move inline style to class.

2021-08-03 14:34 UTC, ewill00 approved these changes
LGTM - you/Brian @cragun47 can fill me in on one of his comments but otherwise I'm good with delivering it.

2021-08-03 16:08 UTC, merged